### ISSUE TITLE
Add alert dialogue for deleting notes

### ISSUE THREAD

**Issue by animsh** [abhinav78910/Note_It#10]
Implement alert dialogue for deleting notes

**Comment by yash37158** [comment]
hey @Me-Abhishek-patel  @animsh  @abhinav78910  may i proceed with this issue , i would like to resolve it?

**Comment by abhinav78910** [comment]
This issue is already assigned to @animsh

**Comment by Haid-Faiz** [comment]
@abhinav78910 can i work on this issue...??
