### ISSUE TITLE
Delete Feature enhacement

### ISSUE THREAD

**Issue by abhinav78910** [abhinav78910/Note_It#5]
Currently inside the app when we swipe any note either to the left/right the note get's deleted immediately. Make a prompt message to the user whether he wants to delete the note or not. The delete functionality must be like shown in the picture below.
![image](https://user-images.githubusercontent.com/51455561/91530976-a3d81600-e929-11ea-8050-a2ce65260303.png)

**Comment by animsh** [comment]
Sir, can I work on this project for hacktoberfest2020?
